baseurl = "http://masiqi.github.io/"
languageCode = "zh-cn"
title = "马思奇的博客"
[permalinks]
  post = "/:year/:month/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Tesla's Awesome Hugo Site"
  author = "Nikola Tesla"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIdAnchors = true
  extensions = ["hardLineBreak"]
